In [2]:
from op import attendance, leave, overtime, utils, supabase, opuser
from pprint import pprint
import pandas as pd

In [2]:
attendance_records = attendance.get_attendance_records_details(
    start_time="2023-08-10 08:00:00",
    end_time="2023-08-10 09:00:00",
)
attendance_records = pd.DataFrame(attendance_records)
attendance_records

,id,opuserid,check_in,miss_check,check_time,check_source
0,297421201620,011513576639885753013,False,True,NaT,NaN
1,298445126848,011513576639885753013,True,True,NaT,NaN
2,297318400936,0119630621012099175733,True,False,2023-08-10 09:11:03,ATM
3,299345890090,0119630621012099175733,False,False,2023-08-10 23:07:13,ATM
4,298410729601,012750346165772386982,True,False,2023-08-10 09:25:22,ATM
...,...,...,...,...,...,...
435,300459195418,2356294751481021497293,False,False,2023-08-10 19:57:55,USER
436,299327490247,235629476128585729843,False,False,2023-08-10 18:31:32,ATM
437,300377617436,235629476128585729843,True,False,2023-08-10 09:07:45,ATM
438,297421201641,23562949295721733623,False,True,NaT,NaN
439,300376936116,23562949295721733623,True,False,2023-08-10 09:03:04,ATM

In [7]:
attendance_records["check_source"].unique()

array([nan, 'ATM', 'USER', 'BOSS'], dtype=object)

In [2]:
overtime_records = overtime.get_overtime_records(
    start_time=utils.get_unix_time(2023, 8, 9),
    end_time=utils.get_unix_time(2023, 8, 12),
)
overtime_records = pd.DataFrame(overtime_records)
overtime_records

,opuserid,record_create_time,status,petty_cash_only,opuser_remark,job_code,expenses,overtime_start_time,overtime_end_time,overtime_duration,location
0,2356183550431614066934,2023-08-11T18:26:00+00:00,COMPLETED,True,- [ ] 住九龙湾，7/8-11/8上环出job，MTR 15.3*10=153,R113,[{'expense_type': 'Travel (Bus/MTR/Non-OT Taxi...,NaN,NaN,NaN,NaN
1,2356285825441193972491,2023-08-11T17:38:00+00:00,COMPLETED,False,None,U051,"[{'expense_type': 'OT Meal', 'expense_amount':...",2023-08-10T20:00:00,2023-08-10T22:02:00,2.0,在客戶公司
2,2356281469311543510842,2023-08-11T17:03:00+00:00,COMPLETED,False,None,T179,"[{'expense_type': 'OT Meal', 'expense_amount':...",2023-08-10T20:00:00,2023-08-10T22:00:00,2.0,在Megabox
3,22144251461220396626,2023-08-11T16:17:00+00:00,COMPLETED,False,None,D114 23IR,"[{'expense_type': 'OT Meal', 'expense_amount':...",2023-08-10T20:00:00,2023-08-11T02:00:00,6.0,在Megabox
4,22144251461220396626,2023-08-11T16:02:00+00:00,COMPLETED,True,MTR from airport,D114 23IR,[{'expense_type': 'Travel (Bus/MTR/Non-OT Taxi...,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
73,235628283269353584094,2023-08-09T00:28:00+00:00,COMPLETED,False,None,U051,"[{'expense_type': 'OT Meal', 'expense_amount':...",2023-08-03T20:00:00,2023-08-03T22:00:00,2.0,在客戶公司
74,235628283269353584094,2023-08-09T00:26:00+00:00,COMPLETED,False,None,U051,"[{'expense_type': 'OT Meal', 'expense_amount':...",2023-08-02T20:00:00,2023-08-02T22:08:00,2.0,在客戶公司
75,235628283269353584094,2023-08-09T00:25:00+00:00,COMPLETED,False,None,U051,"[{'expense_type': 'OT Meal', 'expense_amount':...",2023-08-01T20:00:00,2023-08-01T22:09:00,2.0,在客戶公司
76,235628283269353584094,2023-08-09T00:23:00+00:00,TERMINATED,False,None,U051,"[{'expense_type': 'OT Meal', 'expense_amount':...",2023-08-09T20:00:00,2023-08-09T22:00:00,2.0,在客戶公司
77,22143922392042444504,2023-08-09T00:20:00+00:00,COMPLETED,False,None,C221 22D,"[{'expense_type': 'OT Meal', 'expense_amount':...",2023-08-08T20:00:00,2023-08-09T00:00:00,4.0,在Megabox

In [2]:
leave_records = leave.get_leave_records(
    start_time=utils.get_unix_time(2023, 8, 9),
    end_time=utils.get_unix_time(2023, 8, 10),
)
leave_records = pd.DataFrame(leave_records)
leave_records

,opuserid,record_create_time,status,leave_start_time,leave_end_time,leave_type,leave_duration,opuser_remark
0,2356203928281728168385,2023-08-09T20:49:00+00:00,APPROVED,2023-08-10T09:00:00,2023-08-10T18:30:00,病假,8.5,None
1,235611583320513085396,2023-08-09T18:34:00+00:00,APPROVED,2023-08-25T00:00:00,2023-08-29T00:00:00,年假(天),24.0,大阪旅行
2,214759271271458686,2023-08-09T17:08:00+00:00,APPROVED,2023-08-09T12:00:00,2023-08-09T17:30:00,年假(小時),4.5,None
3,214759271271458686,2023-08-09T17:08:00+00:00,APPROVED,2023-08-09T12:00:00,2023-08-09T15:00:00,年假(小時),2.0,None
4,2147540120930890172,2023-08-09T17:06:00+00:00,APPROVED,2023-08-09T12:00:00,2023-08-09T17:30:00,年假(小時),4.5,None
5,2147540120930890172,2023-08-09T17:06:00+00:00,APPROVED,2023-08-09T12:00:00,2023-08-09T15:00:00,年假(小時),2.0,None
6,2214380937973071385,2023-08-09T17:02:00+00:00,APPROVED,2023-08-09T17:00:00,2023-08-09T18:30:00,年假(小時),1.5,Family matter
7,0141352321611189057115,2023-08-09T14:29:00+00:00,APPROVED,2023-08-25T00:00:00,2023-08-29T00:00:00,年假(天),24.0,None
8,22144251451760382970,2023-08-09T13:38:00+00:00,APPROVED,2023-08-25T00:00:00,2023-08-29T00:00:00,年假(天),24.0,None
9,235627646408-950895968,2023-08-09T13:36:00+00:00,APPROVED,2023-08-14T09:00:00,2023-08-25T18:30:00,年假(小時),85.0,None
10,0141352321611189057115,2023-08-09T13:27:00+00:00,APPROVED,2023-08-09T13:25:00,2023-08-09T18:30:00,病假,4.5,None
11,214759271271458686,2023-08-09T13:15:00+00:00,APPROVED,2023-09-07T00:00:00,2023-09-11T00:00:00,年假(天),24.0,公司旅遊
12,2356291021541933038253,2023-08-09T13:14:00+00:00,APPROVED,2023-08-10T09:00:00,2023-08-10T14:00:00,年假(小時),4.0,办理工作签证
13,23562869542167204003,2023-08-09T12:54:00+00:00,APPROVED,2023-08-25T00:00:00,2023-08-29T00:00:00,年假(天),24.0,員工旅遊-大阪團
14,2356176340482035503888,2023-08-09T12:48:00+00:00,APPROVED,2023-08-21T00:00:00,2023-08-21T00:00:00,年假(天),8.0,None
15,235620081264-755575743,2023-08-09T12:28:00+00:00,APPROVED,2023-08-25T00:00:00,2023-08-29T00:00:00,年假(天),24.0,大阪团
16,235627340410-570131115,2023-08-09T12:28:00+00:00,APPROVED,2023-08-09T09:00:00,2023-08-09T12:00:00,年假(小時),3.0,Leave
17,235627340410-570131115,2023-08-09T12:27:00+00:00,APPROVED,2023-08-08T09:00:00,2023-08-08T10:00:00,年假(小時),1.0,Leave
18,011507382813-1972537998,2023-08-09T12:27:00+00:00,APPROVED,2023-08-25T00:00:00,2023-08-29T00:00:00,年假(天),24.0,員工旅遊 - 大阪團
19,22143922392042444504,2023-08-09T12:21:00+00:00,APPROVED,2023-08-25T00:00:00,2023-08-29T00:00:00,年假(天),24.0,None
20,3164420226-429353649,2023-08-09T12:19:00+00:00,APPROVED,2023-08-25T00:00:00,2023-08-29T00:00:00,年假(天),24.0,None
21,2147540120930890172,2023-08-09T12:10:00+00:00,APPROVED,2023-08-09T12:00:00,2023-08-09T15:00:00,年假(小時),2.0,None
22,214759271271458686,2023-08-09T12:09:00+00:00,APPROVED,2023-08-09T12:00:00,2023-08-09T15:00:00,年假(小時),2.0,None
23,235628283323-2126514172,2023-08-09T10:56:00+00:00,APPROVED,2023-08-10T00:00:00,2023-08-11T00:00:00,年假(天),16.0,None
24,22143922021418741460,2023-08-09T10:44:00+00:00,APPROVED,2023-08-08T09:00:00,2023-08-08T10:00:00,年假(小時),1.0,None
25,235620270326-105122466,2023-08-09T10:33:00+00:00,APPROVED,2023-08-09T09:00:00,2023-08-09T11:00:00,年假(小時),2.0,None
26,022420693151-1319269698,2023-08-09T10:24:00+00:00,APPROVED,2023-08-09T10:00:00,2023-08-09T18:30:00,病假,7.5,None
27,30654261571986110225,2023-08-09T09:52:00+00:00,APPROVED,2023-08-09T09:00:00,2023-08-09T10:00:00,年假(小時),1.0,None
28,23296928491412849558,2023-08-09T09:44:00+00:00,APPROVED,2023-08-09T09:00:00,2023-08-09T10:00:00,年假(小時),1.0,Hour leave
29,235619596609-1384927863,2023-08-09T09:41:00+00:00,APPROVED,2023-08-09T09:00:00,2023-08-09T10:00:00,年假(小時),1.0,None
30,2214392216-1387743878,2023-08-09T09:40:00+00:00,APPROVED,2023-08-09T09:00:00,2023-08-09T10:00:00,年假(小時),1.0,None
31,2356203859541004804390,2023-08-09T09:35:00+00:00,APPROVED,2023-08-09T09:00:00,2023-08-09T10:00:00,年假(小時),1.0,None
32,013329466552-1031490273,2023-08-09T09:35:00+00:00,APPROVED,2023-08-09T09:00:00,2023-08-09T11:00:00,年假(小時),2.0,None
33,2356092656022439648,2023-08-09T09:32:00+00:00,APPROVED,2023-08-09T09:00:00,2023-08-09T10:30:00,年假(小時),1.5,None
34,22143809221913087033,2023-08-09T09:31:00+00:00,APPROVED,2023-08-09T09:00:00,2023-08-09T10:30:00,年假(小時),1.5,None
35,221438091863350368,2023-08-09T09:30:00+00:00,APPROVED,2023-08-09T09:00:00,2023-08-09T10:30:00,年假(小時),1.5,None
36,3242662905552151121,2023-08-09T09:30:00+00:00,APPROVED,2023-08-09T09:00:00,2023-08-09T10:30:00,年假(小時),1.5,None
37,235619603753-1303096028,2023-08-09T09:29:00+00:00,APPROVED,2023-08-09T09:00:00,2023-08-09T10:00:00,年假(小時),1.0,None
38,3003120304-1481261848,2023-08-09T09:25:00+00:00,APPROVED,2023-08-09T09:00:00,2023-08-09T10:00:00,年假(小時),1.0,None
39,2214380937973071385,2023-08-09T09:25:00+00:00,APPROVED,2023-08-09T09:00:00,2023-08-09T10:30:00,年假(小時),1.5,Late
40,2214380948-1019448451,2023-08-09T09:23:00+00:00,APPROVED,2023-08-09T09:00:00,2023-08-09T10:00:00,年假(小時),1.0,None
41,235621245336-455280302,2023-08-09T09:20:00+00:00,APPROVED,2023-08-09T09:00:00,2023-08-09T11:00:00,年假(小時),2.0,None
42,2214425115-882273837,2023-08-09T09:20:00+00:00,APPROVED,2023-08-09T09:00:00,2023-08-09T10:00:00,年假(小時),1.0,None
43,011363346611407137024,2023-08-09T09:18:00+00:00,APPROVED,2023-08-09T09:00:00,2023-08-09T10:30:00,年假(小時),1.5,None
44,260130361026361966,2023-08-09T09:17:00+00:00,APPROVED,2023-08-09T09:00:00,2023-08-09T10:30:00,年假(小時),1.5,None
45,2214425139561281623,2023-08-09T09:16:00+00:00,APPROVED,2023-08-09T09:00:00,2023-08-09T18:30:00,病假,8.5,None
46,2214392212-1656788397,2023-08-09T09:09:00+00:00,APPROVED,2023-08-09T09:00:00,2023-08-09T10:00:00,年假(小時),1.0,None
47,2214392211-1760542779,2023-08-09T09:08:00+00:00,APPROVED,2023-08-09T09:00:00,2023-08-09T10:00:00,年假(小時),1.0,None
48,2356203928281728168385,2023-08-09T09:01:00+00:00,APPROVED,2023-08-09T09:00:00,2023-08-09T18:30:00,病假,8.5,稍後補病假紙
49,23562859004823380188,2023-08-09T08:52:00+00:00,APPROVED,2023-08-09T09:00:00,2023-08-09T10:30:00,年假(小時),1.5,None
50,01102719096134466968,2023-08-09T08:47:00+00:00,APPROVED,2023-08-09T09:00:00,2023-08-09T10:00:00,年假(小時),1.0,None
51,235629001125-2132631940,2023-08-09T08:40:00+00:00,APPROVED,2023-08-09T09:00:00,2023-08-09T13:00:00,年假(小時),4.0,None
52,2214380936-1305627301,2023-08-09T08:33:00+00:00,APPROVED,2023-08-09T09:00:00,2023-08-09T10:00:00,年假(小時),1.0,None
53,235629361112223047937,2023-08-09T08:28:00+00:00,APPROVED,2023-08-09T09:00:00,2023-08-09T18:30:00,病假,8.5,感冒引起发烧
54,2214392219182041544,2023-08-09T08:23:00+00:00,APPROVED,2023-08-09T09:00:00,2023-08-09T18:30:00,病假,8.5,None
55,235629361112223047937,2023-08-09T08:20:00+00:00,TERMINATED,2023-08-09T00:00:00,2023-08-09T00:00:00,年假(天),8.0,感冒发烧
56,235629361112223047937,2023-08-09T08:17:00+00:00,TERMINATED,2023-08-09T00:00:00,2023-08-09T00:00:00,年假(天),8.0,有点发烧
57,23561748386576491990,2023-08-09T08:00:00+00:00,APPROVED,2023-08-09T00:00:00,2023-08-11T00:00:00,年假(天),24.0,Ready for examination

In [3]:
leave_records[leave_records["leave_type"] != "年假(小時)"]

,opuserid,record_create_time,status,leave_start_time,leave_end_time,leave_type,leave_duration,opuser_remark
0,2356203928281728168385,2023-08-09T20:49:00+00:00,APPROVED,2023-08-10T09:00:00,2023-08-10T18:30:00,病假,8.5,None
1,235611583320513085396,2023-08-09T18:34:00+00:00,APPROVED,2023-08-25T00:00:00,2023-08-29T00:00:00,年假(天),24.0,大阪旅行
7,0141352321611189057115,2023-08-09T14:29:00+00:00,APPROVED,2023-08-25T00:00:00,2023-08-29T00:00:00,年假(天),24.0,None
8,22144251451760382970,2023-08-09T13:38:00+00:00,APPROVED,2023-08-25T00:00:00,2023-08-29T00:00:00,年假(天),24.0,None
10,0141352321611189057115,2023-08-09T13:27:00+00:00,APPROVED,2023-08-09T13:25:00,2023-08-09T18:30:00,病假,4.5,None
11,214759271271458686,2023-08-09T13:15:00+00:00,APPROVED,2023-09-07T00:00:00,2023-09-11T00:00:00,年假(天),24.0,公司旅遊
13,23562869542167204003,2023-08-09T12:54:00+00:00,APPROVED,2023-08-25T00:00:00,2023-08-29T00:00:00,年假(天),24.0,員工旅遊-大阪團
14,2356176340482035503888,2023-08-09T12:48:00+00:00,APPROVED,2023-08-21T00:00:00,2023-08-21T00:00:00,年假(天),8.0,None
15,235620081264-755575743,2023-08-09T12:28:00+00:00,APPROVED,2023-08-25T00:00:00,2023-08-29T00:00:00,年假(天),24.0,大阪团
18,011507382813-1972537998,2023-08-09T12:27:00+00:00,APPROVED,2023-08-25T00:00:00,2023-08-29T00:00:00,年假(天),24.0,員工旅遊 - 大阪團
19,22143922392042444504,2023-08-09T12:21:00+00:00,APPROVED,2023-08-25T00:00:00,2023-08-29T00:00:00,年假(天),24.0,None
20,3164420226-429353649,2023-08-09T12:19:00+00:00,APPROVED,2023-08-25T00:00:00,2023-08-29T00:00:00,年假(天),24.0,None
23,235628283323-2126514172,2023-08-09T10:56:00+00:00,APPROVED,2023-08-10T00:00:00,2023-08-11T00:00:00,年假(天),16.0,None
26,022420693151-1319269698,2023-08-09T10:24:00+00:00,APPROVED,2023-08-09T10:00:00,2023-08-09T18:30:00,病假,7.5,None
45,2214425139561281623,2023-08-09T09:16:00+00:00,APPROVED,2023-08-09T09:00:00,2023-08-09T18:30:00,病假,8.5,None
48,2356203928281728168385,2023-08-09T09:01:00+00:00,APPROVED,2023-08-09T09:00:00,2023-08-09T18:30:00,病假,8.5,稍後補病假紙
53,235629361112223047937,2023-08-09T08:28:00+00:00,APPROVED,2023-08-09T09:00:00,2023-08-09T18:30:00,病假,8.5,感冒引起发烧
54,2214392219182041544,2023-08-09T08:23:00+00:00,APPROVED,2023-08-09T09:00:00,2023-08-09T18:30:00,病假,8.5,None
55,235629361112223047937,2023-08-09T08:20:00+00:00,TERMINATED,2023-08-09T00:00:00,2023-08-09T00:00:00,年假(天),8.0,感冒发烧
56,235629361112223047937,2023-08-09T08:17:00+00:00,TERMINATED,2023-08-09T00:00:00,2023-08-09T00:00:00,年假(天),8.0,有点发烧
57,23561748386576491990,2023-08-09T08:00:00+00:00,APPROVED,2023-08-09T00:00:00,2023-08-11T00:00:00,年假(天),24.0,Ready for examination

In [3]:
opusers_details = opuser.get_opusers_details()
opusers_details = pd.DataFrame(opusers_details)
opusers_details

,opuserid,name,name_chinese,phone,email,employee_id,department,rank
0,011363164867487807455,June Liang,梁春娟,+852-69301396,None,None,None,None
1,012314351753-368250697,Keith Lai,黎啟源,+852-92104502,None,None,None,None
2,2707060727-1037595066,Miles Zeng,曾逸淼,+852-68166576,None,None,None,None
3,012540471117-1641702324,Karen Chiu,None,+852-95301509,None,None,None,None
4,012540442450-1155240308,Lizze Fang,方彥曉,+852-95001531,None,None,None,None
...,...,...,...,...,...,...,...,...
294,23562949295721733623,Carman.Ng,吳紫敏,+852-56261735,carman.ng@zhcpa.hk,None,HK Internship,HK Internship
295,235629476128585729843,Crystal.Yim,嚴嘉琳,+852-67069235,crystal.yim@zhcpa.hk,None,HK Internship,HK Internship
296,2356294751481021497293,Selwyn.Wong,None,+852-92341463,selwyn.wong@zhcpa.hk,157,Principal,Principal
297,570663600639971890,CN-Andrew.Hong,None,+86-13432850461,None,None,CN Internship,CN Internship
298,2356274565361419909827,Leonard.Yap,None,+60-177518837,leonard.yap@zhcpa.my,None,Audit (MY),Audit (MY)